version: "3"
services:
  database:
    image: mysql
    restart: always
    ports :
     - "9999:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "bookcount"
      MYSQL_PASSWORD: "12345678"
      MYSQL_HOST : "127.0.0.1"
    volumes:
      - mysql-data:/var/lib/mysql

  book-application:  # Image name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8081"
volumes:
  mysql-data:
    driver: local




#
#    httpd:
#      container_name: webserver
#      build: ./webserver/
#      ports:
#        - 80:80
#      links:
#        - mysql
#        - mysql2
#      volumes_from:
#        - app
#
#    mysql:
#      container_name: sqlserver
#      image: mysql:latest
#      ports:
#        - 3306:3306
#      volumes:
#        - ./sqlserver:/docker-entrypoint-initdb.d
#      environment:
#        MYSQL_ROOT_PASSWORD: root
#        MYSQL_DATABASE: dbname1
#        MYSQL_USER: dbuser
#        MYSQL_PASSWORD: dbpass
#
#    mysql2:
#      extends: mysql
#      container_name: sqlserver2
#      environment:
#        MYSQL_ROOT_PASSWORD: root
#        MYSQL_DATABASE: dbname2
#        MYSQL_USER: dbuser
#        MYSQL_PASSWORD: dbpass
#
#    app:
#      container_name: webdata
#      image: php:latest
#      volumes:
#        - ../php:/var/www/html
#      command: "true"