db:   #database service
  drivername : "mysql"
  username : "root"
  password : "12345678"
  host : "0.0.0.0"
  port : "8999"
  dbname : "userstore"
#key:
#  jwtKey: "secretKey"
#port: localhost:9099
